{
 "title": "MarketData Simple Pipeline SKO",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Cassandra DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Price BTC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "trades ",
     "columnId": "symbol",
     "columnTime": "trade_timestamp",
     "columnValue": "price",
     "keyspace": "market",
     "table": "trades",
     "target": "SELECT symbol, trade_timestamp, price FROM market.trades;\n\n\n"
    }
   ]
  },
  {
   "title": "Volume BTC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "columnTime": "trade_timestamp",
     "keyspace": "market",
     "table": "trades",
     "target": "SELECT symbol, trade_timestamp, volume FROM market.trades;\n"
    }
   ]
  },
  { "title": "System Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Object Count by Bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "purefb_buckets_object_count{instance=\"fb\", name=\"finnhub-raw\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "purefb_buckets_object_count{instance=\"fb\", name=\"finnhub-ingest\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Finnhub-raw Object Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(purefb_buckets_object_count{instance=\"fb\", name=\"finnhub-raw\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Object Count Growth by Bucket",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "purefb_buckets_object_count{instance=\"fb\", name=\"finnhub-raw\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Compute System CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "expr": "max by(mode) (node_cpu_seconds_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FB S3 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "purefb_array_s3_performance_latency_usec{instance=\"fb\", dimension=\"usec_per_read_bucket_op\"}",
     "legendFormat": "Read Latency"
    },
    {
     "expr": "purefb_array_s3_performance_latency_usec{instance=\"fb\", dimension=\"usec_per_write_bucket_op\"}",
     "legendFormat": "Write Latency"
    },
    {
     "expr": "purefb_array_s3_performance_latency_usec{instance=\"fb\", dimension=\"usec_per_other_op\"}",
     "legendFormat": "Other Latency"
    }
   ]
  },
  {
   "title": "FB S3 Throughput",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(purefb_array_performance_average_bytes{dimension=\"bytes_per_write\",instance=\"fb\",job=\"fb_om_export_array\"})",
     "legendFormat": "Writes"
    },
    {
     "expr": "sum(purefb_array_performance_average_bytes{dimension=\"bytes_per_op\",instance=\"fb\",job=\"fb_om_export_array\"})",
     "legendFormat": "Other"
    },
    {
     "expr": "sum(purefb_array_performance_average_bytes{dimension=\"bytes_per_read\",instance=\"fb\",job=\"fb_om_export_array\"})",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "FB S3 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "purefb_array_performance_latency_usec{dimension=\"usec_per_write_op\",instance=\"fb\",job=\"fb_om_export_array\",protocol=\"S3\"}",
     "legendFormat": "Write Latency"
    },
    {
     "expr": "purefb_array_performance_latency_usec{dimension=\"usec_per_read_op\",instance=\"fb\",job=\"fb_om_export_array\",protocol=\"S3\"}",
     "legendFormat": "Read Latency"
    },
    {
     "expr": "purefb_array_performance_latency_usec{dimension=\"usec_per_other_op\",instance=\"fb\",job=\"fb_om_export_array\",protocol=\"S3\"}",
     "legendFormat": "Other Latency"
    }
   ]
  }
 ]
}